#!/bin/sh

tab="	"

showhelp()
{
	cat <<EOF 1>&2
Usage: $(basename $0) [-h] [-r] [archname]

	-h  Show this help message.
	-r  Reverse; translate Debian names to GNU names. Requires archname.

If archname is not given, the current architecture name is used.
EOF
}

while getopts 'hr' o
do
	case "$o" in
		r)
			reverse=0
			;;
		?|h)
			showhelp
			exit 1
			;;
	esac
done

unset o
cputable=/usr/share/dpkg/cputable

if [ ! -f "$cputable" ]
then
	cat <<EOF 1>&2
It appears that dpkg is not installed on your system.
Install dpkg from your package manager, then try again.
EOF
	exit 1
fi

if [ -n "$(eval "echo \${$OPTIND}")" ]
then
	archname="$(eval "echo \${$OPTIND}")"
else
	if (exit ${reverse:-1})
	then
		echo 'Architecture name required' 1>&2
		showhelp
		exit 1
	fi
	archname="$(uname -m)"
fi

if (exit ${reverse:-1})
then
	field1="$archname"
	field2="[^$tab]+"
	selector='\2'
else
	field1="[^$tab#]+"
	field2="$archname"
	selector='\1'
fi

grep -E -e "^[^#]" "$cputable" | grep -E -e "^${field1}${tab}+${field2}(${tab}+[^${tab}]+){3}$" | sed -E -e "s/^([^$tab]+)$tab+([^$tab]+)($tab+[^$tab]+){3}$/$selector/"
