#!/bin/sh

b0="$(basename $0)"
distrib=UNRELEASED
file=/dev/stdout

showhelp()
{
	cat <<EOF 1>&2
Usage: $b0 [options] [deb|rpm]

	-D format  Output version date in given format, then exit; requires -v.
	-b         Output commit message body, then exit; requires -v.
	-d distrib Fallback distribution for deb format; defaults to "$distrib".
	-h         Show this help message.
	-n name    Name of package; required for deb format.
	-o file    Output to file instead of stdout.
	-r repo    Retrieve log from remote repository.
	-s         Skip log generation for unknown/unspecified package format.
	-t         Try local repository, then remote repository; requires -r.
	-v version Version of package; defaults to latest version.
EOF
}

cleanup()
{
	[ -n "$tmpdir" ] && rm -rf "$tmpdir"
	unset tmpdir
	unset prevdir
}

remotelog()
{
	[ -z "$prevdir" ] && prevdir="$(pwd)"
	[ -z "$tmpdir" ] && tmpdir="/tmp/$(basename "$repo" | sed -E -e 's/\.git//')"
	[ ! -d "$tmpdir" ] && git clone --bare "$repo" "$tmpdir"
	cd "$tmpdir"
	if ! env LANG=C git log "$@"
	then
		cd "$prevdir"
		cleanup
		exit 1
	fi
	cd "$prevdir"
}

log()
{
	if (exit ${trylocal:-1})
	then
		if [ -z "$repo" ]
		then
			echo 'You must specify -r in order to use -t' 1>&2
			showhelp
			exit 1
		fi
		env LANG=C git log "$@" || remotelog "$@"
	elif [ -n "$repo" ]
	then
		remotelog "$@"
	else
		env LANG=C git log "$@"
	fi
}

getversiondate()
{
	if [ -n "$2" ]
	then
		fmtspec='%ad'
	else
		fmtspec='%aD'
	fi
	[ -n "$1" ] && log --grep="^$1$" --date="format:$2" --pretty="format:$fmtspec"
	unset fmtspec
}

logfmt()
{
	log --grep="^$1$" --date="format:$datefmt" --pretty="format:$prettyfmt"
}

getmetadata()
{
	logfmt "$1" | grep -E -e "^[+-] [*_]$2[*_]: " | sed -E -e 's/^[+-] [*_][^*_]+[*_]: (.+)$/\1/'
}

while getopts 'D:bd:hn:o:r:stv:' o
do
	case "$o" in
		v)
			version="$OPTARG"
			;;
		t)
			trylocal=0
			;;
		s)
			skiplog=0
			;;
		r)
			repo="$OPTARG"
			;;
		o)
			file="$OPTARG"
			;;
		n)
			name="$OPTARG"
			;;
		d)
			distrib="$OPTARG"
			;;
		b)
			body=0
			;;
		D)
			format="$OPTARG"
			;;
		?|h)
			showhelp
			exit 1
			;;
	esac
done

if [ -n "$format" ]
then
	if [ -z "$version" ]
	then
		echo 'You must specify -v in order to use -D' 1>&2
		showhelp
		exit 1
	fi
	getversiondate "$version" "$format" > "$file"
	cleanup
	exit
fi

if (exit ${body:-1})
then
	if [ -z "$version" ]
	then
		echo 'You must specify -v in order to use -b' 1>&2
		showhelp
		exit 1
	fi
	log --grep="^${version}$" --pretty="format:%b" > "$file"
	cleanup
	exit
fi

case "$(eval "echo \${$OPTIND}")" in
	deb)
		if [ -z "$name" ]
		then
			echo 'You must specify -n for deb format' 1>&2
			showhelp
			exit 1
		fi
		prettyfmt='%%NAME%% (%s) %%DISTRIBUTIONS%%; %%METADATA%%%n%n%b%n -- %an <%ae>  %aD%n'
		skip='^%NAME%|^ --'
		bullet='  \* '
		leader='  \1'
		;;
	rpm)
		datefmt='%a %b %d %Y'
		prettyfmt='* %ad %an <%ae> - %s%n%b'
		skip='^\*'
		bullet='- '
		leader="$bullet"
		;;
	*)
		! (exit ${skiplog:-1}) && log --until="$(getversiondate "$version")" > "$file"
		cleanup
		exit
		;;
esac

last="$(log --pretty="format:%s" --until="`getversiondate "$version"`" | tail -n 1)"

while read -r s
do
	distributions="$(getmetadata "$s" distributions)"
	urgency="$(getmetadata "$s" urgency)"
	logfmt "$s" | sed -E -e '/^[+-] [*_][^*_]+[*_]: /d' -e "s/^[+-] /$bullet/" -e "/($skip|^$bullet|^[[:space:]]*$)/!{s/^/$bullet/}" -e "s/^$bullet( *[+-] )/\1/" -e "s/(^ +[+-] )/$leader/" | preprocess NAME="$name" DISTRIBUTIONS="${distributions:-$distrib}" METADATA="urgency=${urgency:-medium}"
	[ "$s" != "$last" ] && echo
done <<EOF > "$file"
$(log --pretty="format:%s" --until="`getversiondate "$version"`")
EOF

cleanup
