#!/bin/sh

b0="$(basename $0)"
file=/dev/stdout

showhelp()
{
	cat <<EOF > /dev/stderr
Usage: $b0 [options] [deb|rpm]

	-D format  Output version date in given format, then exit; requires -v.
	-d distrib Distribution; needed for deb format.
	-h         Show this help message.
	-n name    Name of package.
	-o file    Output to file instead of stdout.
	-r repo    Retrieve log from remote repository.
	-s         Skip log generation for unknown/unspecified package format.
	-t         Try local repository, then remote repository; requires -r.
	-v version Version of package; defaults to latest version.
EOF
}

remotelog()
{
	prevdir="$(pwd)"
	tmpdir="/tmp/$(basename "$repo" | sed -E -e 's/\.git//')"
	git clone --bare "$repo" "$tmpdir"
	cd "$tmpdir"
	env LANG=C git log "$@"
	cd "$prevdir"
	rm -rf "$tmpdir"
	unset tmpdir
	unset prevdir
}

log()
{
	if (exit ${trylocal:-1})
	then
		if [ -z "$repo" ]
		then
			echo 'You must specify -r in order to use -t' > /dev/stderr
			showhelp
			exit 1
		fi
		env LANG=C git log "$@" || remotelog "$@"
	elif [ -n "$repo" ]
	then
		remotelog "$@"
	else
		env LANG=C git log "$@"
	fi
}

getversiondate()
{
	if [ -n "$2" ]
	then
		fmtspec='%ad'
	else
		fmtspec='%aD'
	fi
	[ -n "$1" ] && log --grep="^${1}$" --date="format:$2" --pretty="format:$fmtspec"
}

while getopts 'D:d:hn:o:r:stv:' o
do
	case "$o" in
		v)
			version="$OPTARG"
			;;
		t)
			trylocal=0
			;;
		s)
			skiplog=0
			;;
		r)
			repo="$OPTARG"
			;;
		o)
			file="$OPTARG"
			;;
		n)
			name="$OPTARG"
			;;
		d)
			distrib="$OPTARG"
			;;
		D)
			format="$OPTARG"
			;;
		?|h)
			showhelp
			exit 1
			;;
	esac
done

if [ -n "$format" ]
then
	if [ -z "$version" ]
	then
		echo 'You must specify -v in order to use -D' > /dev/stderr
		showhelp
		exit 1
	fi
	getversiondate "$version" "$format" > "$file"
	exit
fi

case "$(eval "echo \${$OPTIND}")" in
	deb)
		prettyfmt='%%NAME%% (%s) %%DEB_DIST%%;%n%b -- %an <%ae>  %aD%n'
		skip='^%NAME%|^ --'
		bullet='  \* '
		leader='  \1'
		;;
	rpm)
		datefmt='%a %b %d %Y'
		prettyfmt='* %ad %an <%ae> - %s%n%b'
		skip='^\*'
		bullet='- '
		leader="$bullet"
		;;
	*)
		! (exit ${skiplog:-1}) && log --until="$(getversiondate "$version")" > "$file"
		exit
		;;
esac

log --date="format:$datefmt" --pretty="format:$prettyfmt" --until="$(getversiondate "$version")" | sed -E -e "s/^[+-] /$bullet/" -e "/($skip|^$bullet|^[[:space:]]*$)/!{s/^/$bullet/}" -e "s/^$bullet( *[+-] )/\1/" -e "s/(^ +[+-] )/$leader/" | preprocess NAME="$name" DEB_DIST="$distrib" > "$file"
