#!/bin/sh

b0=$(basename $0)
file=/dev/stdout

showhelp()
{
	cat <<EOF > /dev/stderr
Usage: $b0 [options] [deb|rpm]

	-d distrib Distribution; needed for deb format.
	-h         Show this help message.
	-n name    Name of package.
	-o file    Output to file instead of stdout.
	-r repo    Retrieve log from remote repository.
EOF
}

log()
{
	if [ -n "$repo" ]
	then
		prevdir=$(pwd)
		tmpdir=$(basename "$repo" | sed -E -e 's/\.git//')
		git clone --bare "$repo" "$tmpdir"
		cd "$tmpdir"
		env LANG=C git log "$@"
		cd "$prevdir"
		rm -rf "$tmpdir"
		unset tmpdir
		unset prevdir
	else
		env LANG=C git log "$@"
	fi
}

while getopts 'd:hn:o:r:' o
do
	case "$o" in
		r)
			repo="$OPTARG"
			;;
		o)
			file="$OPTARG"
			;;
		n)
			name="$OPTARG"
			;;
		d)
			distrib="$OPTARG"
			;;
		?|h)
			showhelp
			exit 1
			;;
	esac
done

case "$(eval "echo \${$OPTIND}")" in
	deb)
		prettyfmt='%%NAME%% (%s) %%DEB_DIST%%;%n%b -- %an <%ae>  %aD%n'
		skip='^%NAME%|^ --'
		bullet='  \* '
		;;
	rpm)
		datefmt='%a %b %d %Y'
		prettyfmt='* %ad %an <%ae> - %s%n%b'
		skip='^\*'
		bullet='- '
		;;
	*)
		log > "$file"
		exit
		;;
esac

log --date="format:$datefmt" --pretty="format:$prettyfmt" | sed -E -e "s/^[+-] /$bullet/" -e "/($skip|^$bullet|^[[:space:]]*$)/!{s/^/$bullet/}" | preprocess NAME="$name" DEB_DIST="$distrib" > "$file"
