#!/bin/sh

b0="$(basename $0)"

showhelp()
{
	cat <<EOF 1>&2
Usage: $b0 [options] [MACRO=value...]

	-c prefix Set comment prefix for #file# directive.
	-d dest   Instead of editing source in place, copy to dest then edit;
	          requires -s.
	-e chars  Escape these characters when using @MACRO@ directive
	-h        Show this help message.
	-s source Source file; edited in place by default.

If neither -s nor -d are specified, stdin and stdout are used.
EOF
}

while getopts 'c:d:e:hs:' o
do
	case "$o" in
		s)
			source="$OPTARG"
			;;
		e)
			chars="$OPTARG"
			;;
		d)
			dest="$OPTARG"
			;;
		c)
			prefix="$(echo "$OPTARG" | sed -E -e 's/\\/\\\\/g' -e 's/([.^$*+?()[{|])/\\\1/g')"
			;;
		?|h)
			showhelp
			exit 1
			;;
	esac
done

unset o

if [ -n "$source" ]
then
	dest="${dest:-$source}"
else
	if [ -n "$dest" ]
	then
		echo 'You must specify -s in order to use -d' 1>&2
		showhelp
		exit 1
	else
		source='/dev/stdin'
		dest='/dev/stdout'
	fi
fi

input="$(cat "$source")"
output="$input"

for a in $(seq $OPTIND $#)
do
	eval "arg=\${$a}"
	macro="$(echo $arg | sed -E -e 's/^([^=]+)=(.+)$/\1/')"
	value="$(echo $arg | sed -E -e 's/^([^=]+)=(.+)$/\2/')"
	if [ -n "$chars" ]
	then
		evalue="$(echo $arg | sed -E -e 's/^([^=]+)=(.+)$/\2/' -e "s/([$chars])/\\\\\\\\\1/g")"
	else
		evalue="$value"
	fi
	if [ -n "$(echo "$value" | tr -c -d /)" ] || [ -n "$(echo "$evalue" | tr -c -d /)" ]
	then
		output="$(printf "%s" "$output" | sed -e "s:%${macro}%:${value}:g" -e "s:@${macro}@:${evalue}:g")"
	else
		output="$(printf "%s" "$output" | sed -e "s/%${macro}%/${value}/g" -e "s/@${macro}@/${evalue}/g")"
	fi
done

unset evalue
unset value
unset macro
unset arg
unset a

while read -r i
do
	file="$(echo $i | sed -E -e "s|^${prefix}#(.+)#$|\1|")"
	[ -n "$file" ] || continue
	output="$(printf "%s" "$output" | sed -e "\|$i|{r $file" -e 'd}')"
done <<EOF
$(printf "%s" "$input" | grep -E -e "^${prefix}#[^#]+#$")
EOF

unset file
unset i
printf "%s" "$output" > "$dest"
